apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-kustomize-template
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Cheunn-Panaa/Selfservix.git
        revision: HEAD
        directories:
          - path: k8s/apps/*/*/*
  template:
    metadata:
      namespace: "{{path.basename}}"
      name: "{{path[2]}}-{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/Cheunn-Panaa/Selfservix.git
        targetRevision: HEAD
        path: "k8s/apps/{{path[2]}}/overlays/{{path.basename}}"
      destination:
        namespace: "{{path.basename}}"
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true