apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: sample-app
        resources:
          limits:
            cpu: 800m
            memory: 500Mi