apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
nameSuffix: -production

resources:
- ../../base
patchesStrategicMerge:
- deployment-patch.yaml
images:
- name: nanajanashia/argocd-app
  newTag: "1.2"
