apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
nameSuffix: -staging


patchesStrategicMerge:
- deployment-patch.yaml
resources:
- ../../base
images:
- name: nanajanashia/argocd-app
  newTag: "1.2"
